-- One-time Snowflake setup for TailSignal. Run in a Snowsight worksheet as ACCOUNTADMIN.
-- Reuses the MedicareFWA service user (FWA_SVC, key-pair auth) and warehouse (FWA_WH, with its
-- resource monitor), so no new key is needed.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS TAILSIGNAL;
CREATE SCHEMA IF NOT EXISTS TAILSIGNAL.RAW;           -- partner files as loaded
CREATE SCHEMA IF NOT EXISTS TAILSIGNAL.REFERENCE;     -- dbt seeds (taxonomies)
CREATE SCHEMA IF NOT EXISTS TAILSIGNAL.STAGING;       -- dbt views, one per source file
CREATE SCHEMA IF NOT EXISTS TAILSIGNAL.INTERMEDIATE;  -- profiles, breed map, entity-resolution output
CREATE SCHEMA IF NOT EXISTS TAILSIGNAL.CORE;          -- dim_pet, fct_service_event, ...
CREATE SCHEMA IF NOT EXISTS TAILSIGNAL.PRODUCT;       -- k-anonymous data products
CREATE SCHEMA IF NOT EXISTS TAILSIGNAL.QA;

CREATE ROLE IF NOT EXISTS TAILSIGNAL_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE FWA_WH TO ROLE TAILSIGNAL_ROLE;
GRANT USAGE ON DATABASE TAILSIGNAL TO ROLE TAILSIGNAL_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE TAILSIGNAL TO ROLE TAILSIGNAL_ROLE;
GRANT ROLE TAILSIGNAL_ROLE TO ROLE SYSADMIN;
GRANT ROLE TAILSIGNAL_ROLE TO USER FWA_SVC;
